apiVersion: apps/v1
kind: Deployment
metadata:
  name: diabetes-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diabetes-fe
  template:
    metadata:
      labels:
        app: diabetes-fe
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: diabetes-fe-service
spec:
  selector:
    app: diabetes-fe
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer